### PR TITLE
Add ui logic

### PR DESCRIPTION
**Pull request by aravindballa**
I will update the changes in the PR and we can merge it when everything is working.

TODO
- [x] copy to clipboard for the result tabs
- [ ] reveal url

### CODE REVIEW

**Comment by aravindballa** [comment]
Deployed this at - https://elegant-wing-87e847.netlify.com
As this is not merged, we cannot use Github Pages to quickly have a look.

**Comment by EggPool** [comment]
Looks pretty good so far, no remark!

**Comment by hclivess** [comment]
Fantastic

**Comment by aravindballa** [comment]
Disabled the Reveal button for now. 

> Deployed this at - https://elegant-wing-87e847.netlify.com

The link is updated. Please check the validation of fields. And merge if things are good.

**Comment by EggPool** [comment]
Awesome, thanks! Merging.

**Pull request merged**
